import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { dahlia_new, menu, closeMenu } from '../assets';
import { Link } from 'react-router';
const Navbar = () => {
    const [toggle, setToggle] = useState(true);
    const handleClick = () => setToggle(!toggle);
    return (_jsx("div", { className: 'w-full h-[80px] z-10 bg-[#394931] fixed drop-shadow-lg relative rounded-b-2xl', children: _jsxs("div", { className: 'flex justify-between items-center w-full h-full md:max-w-[1240px] m-auto', children: [_jsx(Link, { to: '/', children: _jsxs("div", { className: 'flex items-center', children: [_jsx("img", { src: dahlia_new, alt: "dahlia", className: 'sm:ml-2 ss:ml-2  w-[70px] h-[70px]' }), _jsx("h1", { className: 'ml-1 text-4xl md:text-7xl whitespace-nowrap font-qwitcher', children: "Prone To Wander" })] }) }), _jsx("div", { className: 'flex items-center', children: _jsxs("ul", { className: 'hidden md:flex text-white', children: [_jsx(Link, { to: '/', children: _jsx("li", { children: "Home" }) }), _jsx(Link, { to: '/about', children: _jsx("li", { children: "About" }) }), _jsx("li", { children: "Gallery" })] }) }), _jsx("div", { className: "lg:hidden", onClick: handleClick, children: _jsx("img", { src: menu, alt: "menu", className: 'w-8 h-8 object-contain mr-10' }) }), _jsxs("ul", { className: !toggle ? 'absolute top-0 right-0 bg-[#333333] w-[calc(80%)] rounded-2xl drop-shadow-xl' : 'hidden', children: [_jsx("div", { className: 'lg:hidden absolute top-6 right-0', onClick: handleClick, children: _jsx("img", { src: closeMenu, alt: "closeMenu", className: 'w-8 h-8 object-contain mr-10' }) }), _jsxs("div", { className: 'ml-2 mt-2', children: [_jsx(Link, { to: '/', children: _jsx("li", { children: "Home" }) }), _jsx(Link, { to: '/about', children: _jsx("li", { children: "About" }) }), _jsx("li", { children: "Gallery" }), _jsx("li", { children: "Archive" })] }), _jsx("hr", { className: 'h-px ml-15 mr-15 my-2 bg-gray-400 border-0' }), _jsxs("div", { className: 'flex flex-col', children: [_jsx("button", { className: 'border-gray-400 mr-6 ml-6 my-2 bg-transparent px-6 py-2 hover:bg-white hover:text-black', children: "Login" }), _jsx("button", { className: 'border-none mr-6 ml-6 my-2 mb-4 px-6 py-2 hover:bg-white hover:text-black', children: "Sign Up" })] })] })] }) }));
};
export default Navbar;
